### ISSUE TITLE
About inference

### ISSUE THREAD

**Issue by Sylvia6** [alievk/npbg#17]
Hello, thank you for your excellent work and the open-source code!
I have finetuned your pre-trained model, however, I can not find the way about inference.
I saw inference related settings in your config files, but I can’t use them correctly.
Thank you for your reply!

**Comment by seva100** [comment]
Hi @Sylvia6, thank you for appreciating our work. For inference, you can either use this [generate_dataset.py](https://gist.github.com/seva100/4fe57ab17ebd943fa7614cb0d4d7f982) script, or the interactive viewer (`viewer.py` in the repository). In case you encounter some errors, please post them here.

**Comment by Sylvia6** [comment]
Thank u @seva100 ,  but when I run the viewer_numpy.py file, I can’t rotate my render result. Is there anything I should pay attention to？

**Comment by seva100** [comment]
The rotation should work via holding the left mouse button and dragging. If it does not, can you please post some screenshots here and the console output during dragging?

**Comment by vinodrajendran001** [comment]
Hi @Sylvia6,

I am also facing this error. May I know how you resolved it?
