### ISSUE TITLE
Something wrong about the docker image?

### ISSUE THREAD

**Issue by Sylvia6** [alievk/npbg#22]
Hello, I try to run docker/tools/build.sh, however, I get such error:
Can u help me?

```
+ docker build -t npbg -f ../Dockerfile ..
Sending build context to Docker daemon  15.36kB
Error response from daemon: stat /mnt/vdb/docker/tmp: no such file or directory
+ docker tag npbg root/npbg:latest
Error response from daemon: No such image: npbg:latest
```

**Comment by seva100** [comment]
Hi @Sylvia6, I have to say that I'm not sure what could be the reason, but this [thread](https://github.com/moby/moby/issues/19566) suggests to create the `tmp` directory manually. So can you please try `mkdir /mnt/vdb/docker/tmp`?
