### ISSUE TITLE
Rotate novel view

### ISSUE THREAD

**Issue by JOP-Lee** [alievk/npbg#27]
Hi, thanks for sharing the good work.
it's difficult to rotate the view in the viewer, blur due to too much rotation.
I wonder if there is a view_matrix that can rotate 360 degrees in a certain position, Or is there another way to customize the view's trajectory? (It's not the same trajectory as training)

**Comment by seva100** [comment]
Hi @JOP-Lee, there are a few parameters in the `viewer.py` script that might be of some help:
* `--origin-view`: sets the world origin to the scene center
* `--init_view`: one can specify the name of the training camera based on which the viewer will initialize, or provide a filename to the extrinsics parameters of the new camera to initialize from

You can also use the [`generate_dataset.py`](https://gist.github.com/seva100/4fe57ab17ebd943fa7614cb0d4d7f982) script and specify your novel trajectory in the `--view-matrix` parameter. The script will save a set of rendered pictures along the specified trajectory.
