### ISSUE TITLE
How can I get the 3-channel (RGB) picture of point-descriptors rasterizer result?

### ISSUE THREAD

**Issue by JOP-Lee** [alievk/npbg#28]
Hello, I want to get the RGB rendered picture of points descriptors rasterizer result. Can U tell me how to get it?
![3](https://user-images.githubusercontent.com/24960306/149370010-4b8f0afc-0dfe-4981-88c1-a882a43444fa.png)

**Comment by JOP-Lee** [comment]
@seva100  @alievk

**Comment by seva100** [comment]
Hi @JOP-Lee, sorry for a late reply. I think `--pca` key in the `viewer.py` script should do the job.

**Comment by JOP-Lee** [comment]
> Hi @JOP-Lee, sorry for a late reply. I think `--pca` key in the `viewer.py` script should do the job.

Thanks for your help, I have solved the problem.
