### ISSUE TITLE
How to set num_sample

### ISSUE THREAD

**Issue by JOP-Lee** [alievk/npbg#30]
hi, thanks for sharing good work.  I would like to know how to set the value of num_samples in train_example.yaml, and how is it implemented in the code.

**Comment by JOP-Lee** [comment]
@seva100

**Comment by seva100** [comment]
@JOP-Lee you can set it in `train_dataset_args` section https://github.com/alievk/npbg/blob/355294b628c79b7d3b98ebe4ecd1e03c78adb8cb/configs/train_example.yaml#L27
